### ISSUE TITLE
Investigate options for connecting with Wikidata via JavaScript

### ISSUE THREAD

**Issue by CliffordAnderson** [HeardLibrary/twine-for-wikicite#6]

**Comment by baskaufs** [comment]
Not Javascript but related: #8 , #9

**Comment by baskaufs** [comment]
Looked at [Wikidata Tours](https://www.wikidata.org/wiki/Wikidata:Tours) to see how they work. It looks like they are running a server side PHP script rather than Javascript. It creates the dialog box that guides the user. The item seems to be a real Wikidata item whose statements get cleared each time the page is loaded. Does not look like anything we can replicate since it's server side.

**Comment by baskaufs** [comment]
Actually, I think I'm wrong about it since [this page](https://www.wikidata.org/wiki/Wikidata:How_to_create_Wikidata_Tours/Javascript) says that you can edit a Javascript file to make your own tour.

**Comment by CliffordAnderson** [comment]
Oh, interesting. I'll check out that page as a good starting point. Thanks for the tip!

**Comment by CliffordAnderson** [comment]
Closing as no longer necessary for the current project
