### ISSUE TITLE
replacing English with Chinese in the button text for Get Help and Outro

### ISSUE THREAD

**Issue by cylew** [HeardLibrary/twine-for-wikicite#65]
@baskaufs In the lessons Get Help and Outro, the button text is in English. Could you replace it using the following Chinese text?
learn about gadgets 学习小工具
learn about identifiers 学习标识符
gadgets 小工具
identifiers 标识符
start over 从新开始
quit 停止
In Get Help, there are two options under the video: learn about gadgets and learn about identifiers. Should we consider adding an another navigation option in order to take the listed twelve lessons?

**Comment by baskaufs** [comment]
@cylew Good catch! I forgot about those buttons. I left them there as placeholders while we decided how get_help and the outro should be linked. 

Now that we've straightened that out, they mostly probably need to be deleted since they were just randomly there from whatever page I copied from when I create them. I will try to clean them up and use your translations for any buttons that are left.

**Comment by baskaufs** [comment]
OK, I think I fixed these. Also noticed that the four tildes weren't being rendered in En and Es. 

As far as the navigation in Get Help, I figured that since the only way to get to that page is from the sidebar navigation, users would have that open or know how to access it in order to get back to the page they left. Optimally, we'd keep track of the page they left and send them back there again, but that would involve figuring out how to code that.
