### ISSUE TITLE
Design website framework for WikiCite project

### ISSUE THREAD

**Issue by CliffordAnderson** [HeardLibrary/twine-for-wikicite#7]

**Comment by baskaufs** [comment]
@CliffordAnderson I know that I should know this, but has it been decided how the training videos will be presented? Will they be embedded within the Twine pages, linked out, or something else?

**Comment by CliffordAnderson** [comment]
I'm thinking that they'll be [HTML5 media elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) that play alongside Twine, but do not get embedded into Twine.

**Comment by CliffordAnderson** [comment]
After further research, I am now thinking that we might use [SugarCube](http://www.motoslave.net/sugarcube/2/) to link the images and video with the Twine story. We would stlll need to develop an encompassing web page for the Twine story itself, but SugarCube promises to make it easier to associate our media assets with the story itself.

**Comment by baskaufs** [comment]
I wanted to note as a followup to the discussion at our last meeting about internal links to pages within the story. I took a quick look at [the HTML](view-source:https://heardlibrary.github.io/twine-for-wikicite/) of a [Twine Page](https://heardlibrary.github.io/twine-for-wikicite/). The interpage navigation seem to be controlled using `pid` and `name` attributes of custom `tw-storydata` tags, as opposed to more typical `id` attributes. I can't see any way to link to the pages using the normal URL fragment identifier method (e.g. <https://heardlibrary.github.io/twine-for-wikicite/#statement>). 

That doesn't mean there isn't a way to do it - it just isn't obvious to me. Maybe it's somewhere in the Twine documentation, or maybe they just don't intend for people to leave the Twine environment and come back.

**Comment by CliffordAnderson** [comment]
Would it work to use the [getElementsByName()](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByName) in JavaScript rather than by the fragment identifier method?

**Comment by baskaufs** [comment]
Hmm. I suppose you could do something like this:

1. Link out to an external page using a link with a query string (i.e. following a `?` in the URL) that includes the information about the current Twine page element, passing the identifier to the external page.
2. When the external page is done doing its thing, it dynamically generates the link back to the Twine page and again inserts the information about the Twine page element as part of a query sting.
3. In the Twine page, have page-load Javascript that accepts the passed-in data about the element. That Javascript would then have to handle making the Twine Javascript load/display the Twine page element corresponding to the passed-in data. 

This last part is what is unclear to me. I haven't worked with Javascript much for several years, so I'd have to research how to code this (maybe using `.getElementsByName`?). I know that Twine has capabilities for stuff like tracking what pages have been visited, etc. so if that information can be accessed by custom Javascript, it could be possible.

**Comment by baskaufs** [comment]
@CliffordAnderson @cylew @awesolek2 @marjans74 @Talinum  Please take a look at the styled pages. The links to the test pages are on the [GitHub landing page](https://github.com/HeardLibrary/twine-for-wikicite), labeled "Style test (language)". Don't worry about the fact that the button labels and reference links at the bottom are not yet in the target language (we will need to fix that later). Just see if the style fits what we discussed yesterday. 

There is a lot of wasted vertical space that I don't know how to reduce -- I think it's built-in to the web design. So I guess I'll just live with it, even though it annoys me (as a believer of functionality over design).

I decided to put the further information links (fake in this example, not every page will necessarily have them) in the next section after the TLDR bullet points. I like the way putting them in that section sets them off from the TLDR and it was easier to do based on the CSS that the web designer set up. The only thing I'm not sure about is the color of the hyperlinked text. I used the orange theme color to match other elements in the theme. I'm not sure that I like how it looks but I think it shows up better than any other theme color. We could just use a non-theme color like yellow or another light color to contrast with the dark blue background of that section, but I'm not sure that would be better. 

We still need to fix the page response to increasing width, but since that should be fixable for every page using the CSS, if I get a thumbs up on this design, I can start proliferating it to all of the passages/pages we have done so far.

**Comment by marjans74** [comment]
Steve,  I think it looks good!
